### ISSUE TITLE
Error:  Could not automatically determine credentials.

### ISSUE THREAD

**Issue by hollyjack123** [graysonw/target-bigquery#2]
Hi, This error seems to be this target-bigquerry is using a few old version libraries. So, how can I fix this error? I encountered the error like this:
   ```
 raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://developers.google.com/accounts/docs/application-default-credentials.
```
And when I install target-bigquery, this is [the error](https://drive.google.com/open?id=1wkJ9i5xTfLgISb-3UjXVLcF4g7ahFx1t)

**Comment by ghost** [comment]
The messages you're seeing during install (the messages in your screenshot) aren't errors, but warnings.  I see them on some of the environments I have executing production workloads here at RealSelf, but they don't seem to be consequential.

As for the credentials error, my recommendation is to use target-bigquery with a service account.  You should download the client_secrets.json file for the service account, making sure it's placed on the machine where you will be running target-bigquery, and setting the GOOGLE_APPLICATION_CREDENTIALS environment variable on that machine to the path of the client_secrets.json file.

**Comment by hollyjack123** [comment]
Thanks for your answer. I followed it and I'm still having another problem, and it like this:

`google.auth.exceptions.DefaultCredentialsError: The file /home/******/*****/My_Project/client_secret.json does not have a valid type. Type is None, expected one of ('authorized_user', 'service_account').`

I'm sure that the `client_secret.json` is correct and placed at right place.
Did I forget something? Thanks.

**Comment by ghost** [comment]
You'll need to set the type to 'service_account'.  I don't recall exactly where that type gets set though.

**Comment by hollyjack123** [comment]
Hi, rsmichaeldunn.
The READ.ME document went wrong. You should create a _**`Service account key`**_ instead _`OAuth client ID`_ at **Step 1**.

**Comment by hollyjack123** [comment]
I just found that the target-bigquery have an error.  In the first time, if you stream 100 users, the Big Query will receive 99 users only. Lost the first user.

**Comment by ghost** [comment]
You can do either oAuth (or could at the time) or service account.  I just recommend the service account because it's simpler.  This isn't really an issue with the target so much as this is how you authenticate with the GCP API in general.  The target is making the assumption that the environment where you run the tap is already configured to communicate with the API.

Feel free to fork the repo and submit a PR with the changes you think ought to be made.  My team and I do our best to support this, but it's purely a spare time thing.

As for the error you're reporting, please open a new issue for that, with details.  There's not a lot that can be done to troubleshoot a potential problem with what you've posted about it so far.
