### ISSUE TITLE
Not receive enough data in the first stream. 

### ISSUE THREAD

**Issue by HansonVPHAM** [graysonw/target-bigquery#3]
In the first stream, I didn't receive full data. If I sent 10 user records, I will receive 9 user records only on bigquery. But it didn't occur in the next stream.

**Comment by ghost** [comment]
- If you're seeing errors, please paste the error text.
- Is there a pattern to which record(s) is(are) missing?
  - Is it always the first or last record?
  - Is it a (seemingly) random record?
- Are you running the target in stream mode or job mode? (This is determined by the value of stream_data in your config file)
- Have you ruled out problems with the tap by:
  - Running the target with a different tap?
  - Feeding the data from your tap to a different target like target-csv?

If you're running the target in job mode, you might try editing the target-bigquery.py to write the temporary file out to a normal file before the BQ job runs [here](https://github.com/RealSelf/target-bigquery/blob/master/target_bigquery.py#L171) and see if there's anything that stands out in the file (like, most importantly, whether the file has the right number of records).  From the order of ifs (if record, elif state, elif schema) it seems as though if the tap emits a record message before a schema message, the target might omit that first record, because it hasn't created the temporary file for the record to go into yet.

**Comment by HansonVPHAM** [comment]
I'm running the target in stream mode to send 2,000 records to Bigquery, It's can run fine. But Sometimes, something makes it stuck. I mean It's running well and suddenly it freezes and no longer works (not break) without error message! I don't know why. But I think the error appeared at this line code (216): 
`errors[msg.stream] = bigquery_client.create_rows(tables[msg.stream], [msg.record])`
What will happen if this above line code encounter with the errors (403, 500, 503)? Will it retry or it will stop the stream?
I tried my tap with target-gsheet and it worked well.

**Comment by ghost** [comment]
have you tried running it as a job instead of streaming the data?
